/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vistas;

import java.util.Date;
import javax.swing.JOptionPane;
import proyectofinalhotel71.accesoADatos.HabitacionData;
import proyectofinalhotel71.accesoADatos.TipoDeHabitacionData;
import proyectofinalhotel71.entidades.Habitacion;
import proyectofinalhotel71.entidades.TipoDeHabitacion;

/**
 *
 * @author Bello
 */
public class RegistroDeHabitaciones extends javax.swing.JInternalFrame {

    /**
     * Creates new form RegistroDeHabitaciones
     */
    private TipoDeHabitacionData thData = new TipoDeHabitacionData();
    private TipoDeHabitacion tipoDeHabitacionNueva = null;
    private HabitacionData hData = new HabitacionData();
    private Habitacion habitacionNueva = null;

    public RegistroDeHabitaciones() {
        initComponents();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jcBoxCantPersonas = new javax.swing.JComboBox<>();
        jcBoxCantCamas = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtIdCategoria = new javax.swing.JTextField();
        jcBoxTipoHabitacion = new javax.swing.JComboBox<>();
        jLabel7 = new javax.swing.JLabel();
        jrbEstado = new javax.swing.JRadioButton();
        jBGuardar = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtPrecio = new javax.swing.JTextField();
        jcBoxTipoCamas = new javax.swing.JComboBox<>();
        jbBuscarIdCategoria = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jBSalir = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jtIdCategoria2 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jtPiso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jrbHabDisponible = new javax.swing.JRadioButton();
        jbGuardarHabitacion = new javax.swing.JButton();
        jbDesHabilitar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        jtIdHabitacion = new javax.swing.JTextField();
        jbBuscarIdHabitacion = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("REGISTRO DE HABITACIONES"));

        jLabel2.setText("CANT. PERSONAS");

        jLabel3.setText("CANT. CAMAS");

        jLabel4.setText("TIPO DE CAMAS");

        jcBoxCantPersonas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4" }));
        jcBoxCantPersonas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBoxCantPersonasActionPerformed(evt);
            }
        });

        jcBoxCantCamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3" }));

        jLabel5.setText("TIPO DE HABITACION");

        jLabel6.setText("ID CATEGORIA");

        jtIdCategoria.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdCategoriaKeyTyped(evt);
            }
        });

        jcBoxTipoHabitacion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "SIMPLE", "DOBLE", "TRIPLE", "SUITE LUJO" }));
        jcBoxTipoHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBoxTipoHabitacionActionPerformed(evt);
            }
        });

        jLabel7.setText("ESTADO");

        jrbEstado.setText("DISPONIBLE");

        jBGuardar.setText("GUARDAR");
        jBGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBGuardarActionPerformed(evt);
            }
        });

        jLabel8.setText("PRECIO POR NOCHE");

        jtPrecio.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPrecioKeyTyped(evt);
            }
        });

        jcBoxTipoCamas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Seleccione el tipo", "SIMPLE", "QUEEN", "KING SIZE" }));
        jcBoxTipoCamas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jcBoxTipoCamasActionPerformed(evt);
            }
        });

        jbBuscarIdCategoria.setText("BUSCAR");
        jbBuscarIdCategoria.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarIdCategoriaActionPerformed(evt);
            }
        });

        jButton2.setText("ELIMINAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("LIMPIAR CAMPOS");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jBSalir.setText("SALIR");
        jBSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton3)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel7)
                                .addComponent(jLabel8)))
                        .addGap(18, 18, 18)
                        .addComponent(jBGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jBSalir))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(182, 182, 182)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jrbEstado)
                            .addComponent(jcBoxCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jcBoxCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, 88, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jcBoxTipoCamas, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jcBoxTipoHabitacion, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4))
                                .addGap(211, 211, 211)
                                .addComponent(jbBuscarIdCategoria))
                            .addComponent(jLabel5))))
                .addContainerGap(21, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(jtIdCategoria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarIdCategoria))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jcBoxCantPersonas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jcBoxCantCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jcBoxTipoCamas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jcBoxTipoHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(jtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jrbEstado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 79, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jBGuardar)
                    .addComponent(jButton3)
                    .addComponent(jButton2)
                    .addComponent(jBSalir))
                .addGap(58, 58, 58))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("HABITACION"));

        jtIdCategoria2.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdCategoria2KeyTyped(evt);
            }
        });

        jLabel1.setText("ID CATEGORIA");

        jLabel9.setText("PISO");

        jtPiso.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtPisoKeyTyped(evt);
            }
        });

        jLabel10.setText("ESTADO");

        jrbHabDisponible.setText("DISPONIBLE");

        jbGuardarHabitacion.setText("GUARDAR");
        jbGuardarHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbGuardarHabitacionActionPerformed(evt);
            }
        });

        jbDesHabilitar.setText("DESHABILITAR");
        jbDesHabilitar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbDesHabilitarActionPerformed(evt);
            }
        });

        jLabel11.setText("NRO HABITACION");

        jtIdHabitacion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jtIdHabitacionKeyTyped(evt);
            }
        });

        jbBuscarIdHabitacion.setText("BUSCAR");
        jbBuscarIdHabitacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbBuscarIdHabitacionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jrbHabDisponible, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jtIdCategoria2)
                            .addComponent(jtPiso)))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(39, 39, 39)
                            .addComponent(jbGuardarHabitacion)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jbDesHabilitar))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(jLabel11)
                            .addGap(18, 18, 18)
                            .addComponent(jtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(18, 18, 18)
                            .addComponent(jbBuscarIdHabitacion))
                        .addComponent(jSeparator1, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(jtIdHabitacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbBuscarIdHabitacion))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtIdCategoria2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jtPiso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jrbHabDisponible))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbGuardarHabitacion)
                    .addComponent(jbDesHabilitar))
                .addGap(148, 148, 148))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jcBoxCantPersonasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBoxCantPersonasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBoxCantPersonasActionPerformed

    private void jBGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBGuardarActionPerformed
        // TODO add your handling code here:
        try {

            Integer cantPersonas = Integer.parseInt(jcBoxCantPersonas.getSelectedItem().toString());
            Integer cantCamas = Integer.parseInt(jcBoxCantCamas.getSelectedItem().toString());
            String tipoCamas = jcBoxTipoCamas.getSelectedItem().toString();
            String tipoDeHabitacion = jcBoxTipoHabitacion.getSelectedItem().toString();
            Integer precio = Integer.parseInt(jtPrecio.getText().toString());
            Boolean estado = jrbEstado.isSelected();
            if (tipoDeHabitacionNueva == null) {

                tipoDeHabitacionNueva = new TipoDeHabitacion(cantPersonas, cantCamas, tipoCamas, tipoDeHabitacion, precio, estado);
                thData.altaTipoHabitacion(tipoDeHabitacionNueva);

            } else {

                tipoDeHabitacionNueva.setCantPersonas(cantPersonas);
                tipoDeHabitacionNueva.setCantCamas(cantCamas);
                tipoDeHabitacionNueva.setTipoCamas(tipoCamas);
                tipoDeHabitacionNueva.setTipoDeHabitacion(tipoDeHabitacion);
                thData.altaTipoHabitacion(tipoDeHabitacionNueva);

            }

        } catch (NumberFormatException ex) {

            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }

        limpiarCampos();
    }//GEN-LAST:event_jBGuardarActionPerformed

    private void jcBoxTipoHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBoxTipoHabitacionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBoxTipoHabitacionActionPerformed

    private void jcBoxTipoCamasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jcBoxTipoCamasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jcBoxTipoCamasActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        limpiarCampos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jBSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBSalirActionPerformed
        // TODO add your handling code here:
        int confirmacion = JOptionPane.showConfirmDialog(null, "¿Esta seguro que desea salir?", "Confirmar salida", JOptionPane.YES_NO_OPTION); //cuadro de dialogo para confirmar salida
        //si el usuario selecciona "No" se cierra solo el cuadro de dialogo
        if (confirmacion == JOptionPane.YES_OPTION) {
            dispose(); //cierra la ventana si el usuario confirma la salida
        }
    }//GEN-LAST:event_jBSalirActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        if (tipoDeHabitacionNueva != null) {

            thData.bajaHabitacion(tipoDeHabitacionNueva.getIdTipoDeHabitacion());
            tipoDeHabitacionNueva = null;
            limpiarCampos();

        } else {

            JOptionPane.showMessageDialog(this, "No hay un Habitacion seleccionada");
        }

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jbBuscarIdCategoriaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarIdCategoriaActionPerformed
        // TODO add your handling code here:
        try {
            Integer idTipoDeHabitacion = Integer.parseInt(jtIdCategoria.getText()); //obtenemos el id
            tipoDeHabitacionNueva = thData.buscarTipoDeHabitacionPorId(idTipoDeHabitacion);
            if (tipoDeHabitacionNueva != null) {

                jcBoxCantPersonas.setSelectedItem(tipoDeHabitacionNueva.getCantPersonas());
                jcBoxCantCamas.setSelectedItem(tipoDeHabitacionNueva.getCantCamas());
                jcBoxTipoCamas.setSelectedItem(tipoDeHabitacionNueva.getTipoCamas());
                jcBoxTipoHabitacion.setSelectedItem(tipoDeHabitacionNueva.getTipoDehabitacion());
                jtPrecio.setText(String.valueOf(tipoDeHabitacionNueva.getPrecio()));
                jrbEstado.setSelected(tipoDeHabitacionNueva.isActivo());

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
        }

    }//GEN-LAST:event_jbBuscarIdCategoriaActionPerformed

    private void jbBuscarIdHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbBuscarIdHabitacionActionPerformed
        // TODO add your handling code here:
        try {
            Integer idHabitacion = Integer.parseInt(jtIdHabitacion.getText()); //obtenemos el id
            habitacionNueva = hData.buscarHabitacionPorId(idHabitacion);
            if (habitacionNueva != null) {

                jtIdCategoria2.setText(String.valueOf(habitacionNueva.getIdTipoDeHabitacion()));
                jtPiso.setText(String.valueOf(habitacionNueva.getPiso()));
                jrbHabDisponible.setSelected(habitacionNueva.isActivo());

            }

        } catch (NumberFormatException ex) {
            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");

    }//GEN-LAST:event_jbBuscarIdHabitacionActionPerformed
    }


    private void jbGuardarHabitacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbGuardarHabitacionActionPerformed
        // TODO add your handling code here:
//        try {
//
//            Integer piso = Integer.parseInt(jtPiso.getText().toString());
//            Boolean estado = jrbHabDisponible.isSelected();
//            if (habitacionNueva == null) {
//
//                habitacionNueva =new Habitacion(piso,idTipoDeHabitacion,estado);
//                hData.agregarHabitacion(habitacionNueva);
//
//            } else {
//
//                habitacionNueva.setPiso(piso);
//                habitacionNueva.setActivo(true);
//                habitacionNueva.setTipoDeHabitacion(idTipoDeHabitacion);
//                hData.agregarHabitacion(habitacionNueva);
//
//            }
//
//        } catch (NumberFormatException ex) {
//
//            JOptionPane.showMessageDialog(this, "Debe ingresar un numero valido");
//        }
//
//        limpiarCampos();


    }//GEN-LAST:event_jbGuardarHabitacionActionPerformed

    private void jbDesHabilitarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbDesHabilitarActionPerformed
        // TODO add your handling code here:
        if (habitacionNueva != null) {

            hData.deshabilitarHabitacion(habitacionNueva.getIdHabitacion());
            habitacionNueva = null;
            limpiarCampos();

        } else {

            JOptionPane.showMessageDialog(this, "No hay un Habitacion seleccionada");
        }
    }//GEN-LAST:event_jbDesHabilitarActionPerformed

    private void jtPrecioKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPrecioKeyTyped
        // TODO add your handling code here:
        
        int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_jtPrecioKeyTyped

    private void jtIdCategoriaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdCategoriaKeyTyped
        // TODO add your handling code here:
        
         int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_jtIdCategoriaKeyTyped

    private void jtIdHabitacionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdHabitacionKeyTyped
        // TODO add your handling code here:
        
         int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_jtIdHabitacionKeyTyped

    private void jtPisoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtPisoKeyTyped
        // TODO add your handling code here:
        
         int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_jtPisoKeyTyped

    private void jtIdCategoria2KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtIdCategoria2KeyTyped
        // TODO add your handling code here:
        
         int key = evt.getKeyChar();

        boolean numero = key >= 48 && key <= 57;

        if (!numero) {
            evt.consume();
        }
    }//GEN-LAST:event_jtIdCategoria2KeyTyped


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jBGuardar;
    private javax.swing.JButton jBSalir;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JButton jbBuscarIdCategoria;
    private javax.swing.JButton jbBuscarIdHabitacion;
    private javax.swing.JButton jbDesHabilitar;
    private javax.swing.JButton jbGuardarHabitacion;
    private javax.swing.JComboBox<String> jcBoxCantCamas;
    private javax.swing.JComboBox<String> jcBoxCantPersonas;
    private javax.swing.JComboBox<String> jcBoxTipoCamas;
    private javax.swing.JComboBox<String> jcBoxTipoHabitacion;
    private javax.swing.JRadioButton jrbEstado;
    private javax.swing.JRadioButton jrbHabDisponible;
    private javax.swing.JTextField jtIdCategoria;
    private javax.swing.JTextField jtIdCategoria2;
    private javax.swing.JTextField jtIdHabitacion;
    private javax.swing.JTextField jtPiso;
    private javax.swing.JTextField jtPrecio;
    // End of variables declaration//GEN-END:variables

    private void limpiarCampos() {

        jtIdCategoria.setText("");
        jcBoxCantPersonas.setSelectedIndex(0);
        jcBoxCantCamas.setSelectedIndex(0);
        jcBoxTipoCamas.setSelectedIndex(0);
        jcBoxTipoHabitacion.setSelectedIndex(0);
        jtPrecio.setText("");
        jrbEstado.setSelected(false);
        jtIdHabitacion.setText("");
        jtIdCategoria2.setText("");
        jtPiso.setText("");
        jrbHabDisponible.setSelected(false);

    }
}
